# Template to launch a devstack setup with networking-opencontrail ml2 plugin

heat_template_version: 2015-04-30

parameters:
  image:
    type: string
    description: Name of image to use for servers
  flavor:
    type: string
    description: Flavor to use for servers
  external_net:
    type: string
    description: ID or name of external network
  server_endpoint:
    type: string
    description: Server endpoint address
  dns_nameservers:
    type: comma_delimited_list
    description: DNS nameservers for the subnet

 # VN Parameters
  dt967u_mgmt_net_name:
    type: string
    description: Name of mgmt network to be created
  dt967u_mgmt_net_cidr:
    type: string
    description: subnet prefix for mgmt network
  dt967u_mgmt_net_gw:
    type: string
    description: gateway for mgmt network

  dt967u_left_net_name:
    type: string
    description: Name of left network to be created
  dt967u_left_net_cidr:
    type: string
    description: subnet prefix for left network
  dt967u_left_net_gw:
    type: string
    description: gateway for left network

  az_1:
    type: string
    description: Availability Zone for agent

resources:
  dt967u_left_net:
    type: OS::Neutron::Net
    properties:
      name: dt967u_left_net

  dt967u_left_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: dt967u_left_net }
      cidr: { get_param: dt967u_left_net_cidr }
      enable_dhcp: true
      gateway_ip: { get_param: dt967u_left_net_gw }

  dt967u_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: external_net }

  dt967u_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: dt967u_router }
      subnet_id: { get_resource: dt967u_left_subnet }

  dt967u_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules: [
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: tcp,
        port_range_min: 1,
        port_range_max: 65535},
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: udp,
        port_range_min: 1,
        port_range_max: 65535},
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: icmp},
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: 132,
        port_range_min: 1,
        port_range_max: 65535},
        {remote_ip_prefix: 0.0.0.0/0,
        protocol: tcp,
        port_range_min: 22,
        port_range_max: 22}]

  port_1:
    type: "OS::Neutron::Port"
    properties:
      network_id: { get_resource: dt967u_mgmt_net }
      fixed_ips:
        - subnet_id: { get_resource: dt967u_mgmt_subnet }
      security_groups: [{ get_resource: dt967u_security_group }]

  port_2:
    type: "OS::Neutron::Port"
    properties:
      network_id: { get_resource: dt967u_left_net }
      fixed_ips:
        - subnet_id: { get_resource: dt967u_left_subnet }
      security_groups: [{ get_resource: dt967u_security_group }]

  left_vm:
    type: OS::Nova::Server
    properties:
      name: left_vm
      image: { get_param: image }
      flavor: { get_param: flavor }
      availability_zone: { get_param: az_1 }
      networks:
        - port: { get_resource: port_1 }
        - port: { get_resource: port_2 }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash

            dhclient ens4
            sudo ip r add $private_net_cidr_2 dev ens4
            sudo ip link set ens4 mtu 9000

            #==external port
            #dhclient ens5
            #==external port
            
          # Steps to install and configure devstack
          sudo apt-get update 
          sudo apt-get -y install git vim-gtk libxml2-dev libxslt1-dev libpq-dev python-pip libsqlite3-dev 
          sudo apt-get -y build-dep python-mysqldb 
          sudo pip install git-review tox 
          
          git config --global user.email "deepak.dt@gmail.com"
          git config --global user.name "Deepak Tiwari"
          git config --global user.editor "vim"
          
          #sudo groupadd stack
          #sudo useradd -g stack -s /bin/bash -d /opt/stack -m stack
          #echo "stack ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/stack
          #sudo su - stack
          
          export WORKSPACE=$PWD
          
          git clone https://github.com/openstack-dev/devstack 
          sudo chown -R ubuntu:ubuntu $WORKSPACE/devstack
          
          cd $WORKSPACE/devstack
          
          # Replace git.openstack.org with https://github.com/openstack in "GIT_BASE=${GIT_BASE:-git://git.openstack.org}"
          str_to_rep_old="git\:\/\/git.openstack.org"
          str_to_rep_new="https\:\/\/git.openstack.org"
          
          sed -n "1h;2,\$H;\${g;s/$str_to_rep_old/$str_to_rep_new/;p}" $WORKSPACE/devstack/stackrc > $WORKSPACE/devstack/stackrc_new
          mv $WORKSPACE/devstack/stackrc_new $WORKSPACE/devstack/stackrc
          
          # Prepare local.conf file
          cat > $WORKSPACE/devstack/local.conf << EOF
          [[local|localrc]]
          ADMIN_PASSWORD=secret
          DATABASE_PASSWORD=\$ADMIN_PASSWORD
          RABBIT_PASSWORD=\$ADMIN_PASSWORD
          SERVICE_PASSWORD=\$ADMIN_PASSWORD
          #Enable heat services
          enable_service h-eng h-api h-api-cfn h-api-cw
          #Enable heat plugin
          enable_plugin heat https://git.openstack.org/openstack/heat stable/newton
          # Neutron - Networking Service
          # If Neutron is not declared the old good nova-network will be used
          ENABLED_SERVICES+=,q-svc,q-agt,q-dhcp,q-l3,q-meta,neutron
          ## Neutron - Load Balancing
          ENABLED_SERVICES+=,q-lbaas
          ## Neutron - VPN as a Service
          ENABLED_SERVICES+=,q-vpn
          ## Neutron - Firewall as a Service
          ENABLED_SERVICES+=,q-fwaas
          # VLAN configuration
          Q_PLUGIN=ml2
          ENABLE_TENANT_VLANS=True
          # GRE tunnel configuration
          Q_PLUGIN=ml2
          ENABLE_TENANT_TUNNELS=True
          # VXLAN tunnel configuration
          Q_PLUGIN=ml2
          Q_ML2_TENANT_NETWORK_TYPE=vxlan 
          IMAGE_URL_SITE="http://download.fedoraproject.org"
          IMAGE_URL_PATH="/pub/fedora/linux/releases/25/CloudImages/x86_64/images/"
          IMAGE_URL_FILE="Fedora-Cloud-Base-25-1.3.x86_64.qcow2"
          IMAGE_URLS+=","\$IMAGE_URL_SITE\$IMAGE_URL_PATH\$IMAGE_URL_FILE
          # Enable Logging
          LOGFILE=/opt/stack/logs/stack.sh.log
          VERBOSE=True
          LOG_COLOR=True
          SCREEN_LOGDIR=/opt/stack/logs
          EOF
          
          sudo chown -R vagrant:vagrant $WORKSPACE/devstack
          
          FORCE=yes ./stack.sh
          
          params:
            "$private_net_cidr_2": { get_param: private_net_cidr_2 }
            "$right_vm_1_ip": { get_attr: [port_2, fixed_ips, 0, ip_address] }
            "$right_vm_2_ip": { get_attr: [port_3, fixed_ips, 0, ip_address] }

outputs:
  left_vm_instance_name:
    value: { get_attr: [ left_vm, instance_name ] }
  left_vm_mgmt_ip:
    value: { get_attr: [ left_vm, networks, { get_attr: [dt967u_mgmt_net, name] }, 0 ] }
  left_vm_left_ip:
    value: { get_attr: [ left_vm, networks, { get_attr: [dt967u_left_net, name] }, 0 ] }
